### ISSUE TITLE
Generator - automaticke pojmenovani instanci

### ISSUE THREAD

**Issue by veselj43** [veselj43/dp-advanced-iterative-methods#10]
- generator by mel vygenerovat jmeno podle parametru a odlisit stejne soubory (kontrola oproti vsem nahranym)

**Comment by Kluzamic** [comment]
Tak nejak hotovo, kouknete na nazvy tech instancich. Zatim to je proste typProblemuVelikost_parametr_parametr. Nedaval sem tam nazvy parametru pac by to byli silene dlouhy jmena pak.

**Comment by Kluzamic** [comment]
Pridal sem pridavani cisla jako je to ve windowsu kdyz stahnete nejakej soubor co uz mate. Takze pokud tam je uz instance co ma tohle jmeno tak ma nakonci (1), (2) atd...
