### ISSUE TITLE
Roztahnuti grafu aby zobrazil všechny výsledky

### ISSUE THREAD

**Issue by Kluzamic** [veselj43/dp-advanced-iterative-methods#12]
Občas se stane že není vidět část průběhu. Stává se to u velkých hodnot nebo velkých rozdílech. Ideálně aby se ten graf zobrazoval jenom v rozmezí kde se něco děje cca.

**Comment by Kluzamic** [comment]
Další problém je, že pokud je fitness / cenová funkce moc velká tak se špatně zobrazujou hodnoty na y ose. buď je to nečitelný nebo tam je všude 100 000. Zkoušel sem to na obchodním cestujícím s drahýma hranama.

**Comment by veselj43** [comment]
Upraveno, podivej se, jestli je to ok nebo tomu jeste neco chybi..

**Comment by Kluzamic** [comment]
Pri vykreslovani to je furt divny, ale ve vysledku v pohode takze asi ok

**Comment by veselj43** [comment]
Jestli myslis vykreslovani jakoze prubeh algoritmu, tak tam jsem to nedelal a asi ani nebudu..
popravde, nechce se mi uz testovat jestli to ma dopad na vykon..

**Comment by Kluzamic** [comment]
No jde jen o to ze vlastne behem prubehu vidis jen tvar cary ale ne tu hodnotu, ale jak rikam nevim jestli to tak moc vadi.
