### ISSUE TITLE
Přidat možnost smazání u každé položky historie

### ISSUE THREAD

**Issue by kugleada** [veselj43/dp-advanced-iterative-methods#16]
Procházel jsem výstupy z NUR a tohle je vytýkáno ve fázi testování a stále to tam není.

**Comment by veselj43** [comment]
Jeste me napada, jestli misto rozklikavani parametru v historii neudelat popover jako u informaci o vstupnich instancich.

**Comment by kugleada** [comment]
Pravda ze by to asi chtelo sjednotit. Otazka je co je lepsi.

**Comment by Kluzamic** [comment]
Tak to zjistíme u testováni asi, možná bych to zatím nechal takhle a můžeme se optat co si myslí, že je lepší.
