### ISSUE TITLE
Zobrazovani hodnot grafu po najeti mysi

### ISSUE THREAD

**Issue by kugleada** [veselj43/dp-advanced-iterative-methods#20]
Nebude lepsi radit zobrazovane hodnoty podle hodnoty nez misto podle umisteni v legende?

**Comment by kugleada** [comment]
Pri najeti na nulu:
GA - funguje spravne a ukaze hodnoty pro pocatecni populaci
Tabu -  0 nezobrazi zadne hodnoty u batohu
SA - 0 zobrazi ruzne hodnoty pro kazdy beh pro batoh. Myslel jsem ze pocatecni stav pouzivas vzdy stejne.

**Comment by veselj43** [comment]
Kouka na to a:
- GA resi objekt spesl - funguje a nevidim tam pripadny problem ve vztahu k ostatnim metodam
- Tabu - chyba byla v tom, ze kontroluju if(value) a kdyz v alue je 0, vraci false... opraveno
- SA - pokud vim, tak pocatecni konfigurace je brana nahodna

**Comment by kugleada** [comment]
Nezmenime jeste to poradi toho popoveru? me by asi vic vyhovovalo aby hodnoty byli serazeny podle toho jak jsou v grafu tedy nejvetsi nahore nejmensi dole

**Comment by veselj43** [comment]
Sry, to jsem zapomnel...
- prijde mi, ze kdyz popojedu do strany a prehazi se mi poradi, ze to bude matouci
- navic pak je otazka, podle ceho to budes radit u GA?

mozna bych pockal na @Kluzamic a uvidime, jinak neni problem to kdyztak rozdelit podle metod

**Comment by kugleada** [comment]
radil bych to primarne podle hodnoty a sekundarne podle typu hodnoty. Obe varianty maji svy pro a proti proto se vas ptam na vas nazor. Me osobne se treba blbe hleda nejlepsi hodnota protoze bych ji cekal nahore. Pravda ze to ze se ti to prehodi muze byt matouci ale zase mas prehled ktery reseni je v danym okazmiku lepsi

**Comment by veselj43** [comment]
Jasne, me to taky napadlo, kdyz jsem to delal. 
Jinak treba nevim jestli nechat barvu na pismu nebo udelat ctverecek vedle, jako je to vsude jinde.
Klidne muzes sepsat vic napadu, jestli mas.. :)

**Comment by kugleada** [comment]
barva na pismu me prijde OK, tyhle detaily zjistime asi az v testovani
