### ISSUE TITLE
Input parametry u metod

### ISSUE THREAD

**Issue by Kluzamic** [veselj43/dp-advanced-iterative-methods#22]
Nevím co se kde předělávalo, ale jakmile teď smažete nějaký parametr(tak že je kolonka prázdná) tak se konzole rozsvítí jak vánoční stromeček.

**Comment by veselj43** [comment]
Zapnul jsem striktni mod ve vuex.. to zpusobi error, kdyz se zedituje stav jinak nez mutaci (napriklad referenci na objekt, coz se tu pravdepodobne deje).
Kouknu na to, kdyby se to stalo jeste nekde, tak dej vedet..

**Comment by veselj43** [comment]
Fixed 4885f88add97bce7250c6ba7b732f0fc61a7dedf
