### ISSUE TITLE
implementace Generatoru

### ISSUE THREAD

**Issue by kugleada** [veselj43/dp-advanced-iterative-methods#23]
Ma nejaky vyznam, ze nejdriv volam konstruktor generatoru s parametry a pak teprve generate bez parametru? nebylo by lepsi volat konstruktor bez parametru a jen volat generate s parametry?

**Comment by Kluzamic** [comment]
Tohle je podle me asi fuk protoze ten objekt stejne jen vytvoris na to jedno generovani a pak se smaze takze to je vlastne to samy. Aspon myslim teda.

**Comment by veselj43** [comment]
Jo, vzdy se vytvari nova instance, protoze se taky vytvari cely worker, takze by ta instance ani nemela kde "zit". 
Jinak podle me:
- Predavat parametry do generate dava smysl, pokud bych generoval vic instanci v jednom behu s ruznymi parametry
- Predavat parametry do konstruktoru dava smysl, pokud chci generovat vice nahodnych instanci se stejnymi parametry

A my nedelame ani jedno, tak nevim podle ceho se rozhodnout :D
