### ISSUE TITLE
Parsovani nahraneho souboru s problemem 

### ISSUE THREAD

**Issue by kugleada** [veselj43/dp-advanced-iterative-methods#24]
Nebylo by lepsi misto metod isInvalidInstance(instanceContent) a resolveInstanceParams(instanceContent) pouzit jednu metodu a ta v pripade uspechu vrati paremetry a v pripade neuspechu treba null?

**Comment by Kluzamic** [comment]
Ja bych to asi nekomplikoval... jo z hlediska nejakyho vykonu je to lepsi ale myslim ze to uplne nema smysl... hlavne par tejdnu pred odevzdanim.

**Comment by veselj43** [comment]
Jako bylo by to hezci, ale realne to nema zadnou pridanou hodnotu...
- soubor se necte vickrat
- parsovani po radkach je rychla a jendoducha operace
- obe metody se volaji jednorazove

Pokud by byl nas use case umet nahravat 100 souboru o 5MB, tak bychom to asi meli predelat, ale uz na urovni, ze se bude ukazovat progress bar nebo tocici kolecko.

Jinak ani to neni napsane prasacky, ma to jednoduchou logiku, takze bych v tom asi nehledal vedu :)
