### ISSUE TITLE
SAT problem ma zvlastni prubeh vypoctu

### ISSUE THREAD

**Issue by veselj43** [veselj43/dp-advanced-iterative-methods#5]
Mozne priciny:
- implementace problemu (hlavne vypocet cenove funkce)
- generovani instanci

**Comment by Kluzamic** [comment]
Opraveno, problem byl ze se generovali moc velky klauzule takze ten problem byl desne jednoduchej. Snizil sem sanci ze promena bude v klauzuli takze by to melo bejt ok
