### ISSUE TITLE
Zobrazovani realnych hodnot v grafu

### ISSUE THREAD

**Issue by veselj43** [veselj43/dp-advanced-iterative-methods#6]
Vytvoreni oddelenych hodnot pro vypocet v algoritmu a pro realne zobrazeni v grafu
- aktualne jsou spatne problemy vertex a TS
- oddeleni by melo probehout obecne, ne jen pro konkretni problemy

**Comment by Kluzamic** [comment]
Funkce na to hotovy, jen je treba je zacit volat v metodach.

**Comment by veselj43** [comment]
Upraveno u Tabu

**Comment by kugleada** [comment]
Upraveno u Genetic

**Comment by veselj43** [comment]
Metody uz funkce pouzivaji, ale u minimal vertex cover problemu jsou spatne zvolene zaporne hodnoty, graf vypada, ze chvili maximalizuje a chvili minimalizuje.
Navrhuju dat misto zapornych hodnot treba pocet uzlu + to jak moc to bylo v zaporu.

**Comment by Kluzamic** [comment]
Předěláno přesně jak říkal Jára, pokud nepokrývá vše tak to vrátí počet uzlů + počet nepokrytejch.
