### ISSUE TITLE
Implementace GA pro TS a doreseni parametru

### ISSUE THREAD

**Issue by veselj43** [veselj43/dp-advanced-iterative-methods#8]
- krizeni a mutace pro permutacni konfiguraci
- doreseni funkcionality parametru (vstupni)
- filtrovani vystupnich parametru (zobrazeni jen pouzityc/relevantnich)

**Comment by kugleada** [comment]
Potreboval bych do Genetic.vue dostat informace o Problemu, jestli je binarni nebo permutacni. Nevim jestli to pujde v soucasne podobe, kdy se problem resi pred enum.

**Comment by veselj43** [comment]
Vytvorena servisa pro ziskani tridy z hodnoty enumu (classResolver) 878409d9f7a0dd6211140f041b359383cfe1016e

**Comment by kugleada** [comment]
Chybi uz jen mutace, kterou musim probrat s Fiserem

**Comment by kugleada** [comment]
Mutace pridana
